#
# Use ubuntu trusty (14.04) with sudo privileges.
dist: trusty
sudo: required
language:
  - generic
cache:
  - apt

language: cpp
compiler:
  - gcc
  
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq gcc-4.7

#check repository
script:
  - cd Disparity_naive
  - make
  - cd ..
  - cd camera_calibration
  - make
  - cd ..
  - cd epipolar_geometry
  - make
  - cd ..
  - cd message_passing
  - make
  - cd ..

